fix #19 target modern JS modules
tastytrade/tastytrade-api-js pull request #30
Opened 2024-02-29 00:55 UTC by osdevisnot

2024-02-29 00:58 UTC, osdevisnot commented
@dmoss18 after this MR is merged, we should publish a new major version to NPM.

2024-02-29 21:31 UTC, dmoss18 requested changes

2024-02-29 21:31 UTC, dmoss18 commented on lib/account-streamer.ts
> +import type { JsonMap, JsonValue } from './utils/json-util.js'
Can you revert all the `.js` suffixes? This is a typescript project. The javascript files should all get compiled into the `dist` folder.

2024-02-29 21:31 UTC, dmoss18 commented
> @dmoss18 after this MR is merged, we should publish a new major version to NPM.

A major version means there would be breaking changes. Have we had any of those? I'd expect this to be a minor release.

2024-02-29 21:49 UTC, osdevisnot commented on lib/account-streamer.ts
> +import type { JsonMap, JsonValue } from './utils/json-util.js'
TS compiler does not rewrite import paths. This is something the TS team has been adamant about. Omitting `.js` extension here will result in an error for all node.js users with ERR_MODULE_NOT_FOUND for the compiled files in dist. See this stack overflow post for more details on this topic - https://stackoverflow.com/a/62626938

Ideally, we would want to adopt a bundler to bundle all the files in dist if we wish to keep extension less imports in src. This however is much larger change!

2024-02-29 21:51 UTC, osdevisnot commented
> > @dmoss18 after this MR is merged, we should publish a new major version to NPM.
> 
> A major version means there would be breaking changes. Have we had any of those? I'd expect this to be a minor release.

I would assume a change in the distribution format `cjs -> esm` as a major change.

2024-03-06 14:30 UTC, dmoss18 commented on lib/account-streamer.ts
> +import type { JsonMap, JsonValue } from './utils/json-util.js'
Can you add some steps to reproduce the issue you are describing?

2024-03-06 18:52 UTC, dmoss18 commented on lib/account-streamer.ts
> +import type { JsonMap, JsonValue } from './utils/json-util.js'
@osdevisnot I see the issue. I'll add a couple things to the tsconfig and we can merge this.

2024-03-06 20:00 UTC, dmoss18 approved these changes

2024-03-06 20:01 UTC, merged